spring:
  datasource:
    url: jdbc:postgresql://pg:5432/studs
    username: ${DB_USER}
    password: ${DB_PWD}
  jpa:
    database: postgresql
    generate-ddl: true
  sql:
    init:
      mode: always
server:
  port: ${PORT:13370}
